feat: convert to composite action using gh api graphql

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,4 +1,4 @@
-name: 'build-test'
+name: 'Test'
 on: # rebuild any PRs and main branch changes
   pull_request:
   push:
@@ -7,40 +7,19 @@ on: # rebuild any PRs and main branch changes
       - 'releases/*'
 
 jobs:
-  build: # make sure build/ci work properly
+  test-branch-on-remote: # make sure the action works on a clean machine without building
     runs-on: ubuntu-latest
     steps:
-      - name: Setup Node.js environment
-        uses: actions/setup-node@v3
-        with:
-          node-version: lts/gallium
-      - uses: actions/checkout@v3
-      - run: yarn install --immutable
-      - run: yarn all
-  test: # make sure the action works on a clean machine without building
-    runs-on: ubuntu-latest
-    steps:
-      - name: Setup Node.js environment
-        uses: actions/setup-node@v3
-        with:
-          node-version: lts/gallium
-      - uses: tibdex/github-app-token@v1
-        id: get_installation_token
-        with:
-          app_id: ${{ secrets.GH_APP_ID }}
-          installation_id: ${{ secrets.GH_APP_INSTALLATION_ID }}
-          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
           ref: ${{ github.head_ref || github.ref }}
-          token: ${{ steps.get_installation_token.outputs.token }}
       - name: Setup test branch
         id: setup-test-branch
         run: |
-          BRANCH_NAME="test-$(date +%s)"
+          BRANCH_NAME="test_on_remote-$(date +%s)"
           
-          git config --global user.name '${{ secrets.GH_APP_USERNAME }}'
-          git config --global user.email '${{ secrets.GH_APP_EMAIL }}'
+          git config --global user.name 'github-actions[bot]'
+          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
           
           git checkout -b $BRANCH_NAME
           git push --set-upstream origin $BRANCH_NAME
@@ -48,6 +27,50 @@ jobs:
           echo $BRANCH_NAME > "test-file.txt"
           echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
       - uses: ./
+        id: test-action
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          stage-all-files: true
+          commit-message: ${{ steps.setup-test-branch.outputs.branch-name }}
+      - name: Delete test branch
+        run: |
+          git push --force --delete origin ${{ steps.setup-test-branch.outputs.branch-name }}
+      - name: Check output
+        run: |
+          changedFilesIfAvailable=$(echo "${{ steps.test-action.outputs.commit-response }}" | jq -r '.data.createCommitOnBranch.commit.changedFilesIfAvailable')
+
+          if [[ -z "$changedFilesIfAvailable" || "$changedFilesIfAvailable" == "null" ]]; then
+            echo "Error: changedFilesIfAvailable is empty or null. Verify the output from test-action."
+            exit 1
+          fi
+
+          if [[ "$changedFilesIfAvailable" -ne 1 ]]; then
+            echo "Error: changedFilesIfAvailable is expected to be 1 but got $changedFilesIfAvailable."
+            exit 1
+          fi
+
+          echo "Validation passed: changedFilesIfAvailable is $changedFilesIfAvailable."
+
+  test-branch-not-on-remote: # make sure the action works on a clean machine without building
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          ref: ${{ github.head_ref || github.ref }}
+      - name: Setup test branch
+        id: setup-test-branch
+        run: |
+          BRANCH_NAME="test_not_on_remote-$(date +%s)"
+          
+          git config --global user.name 'github-actions[bot]'
+          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+          
+          git checkout -b $BRANCH_NAME
+          
+          echo $BRANCH_NAME > "test-file.txt"
+          echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
+      - uses: ./
+        id: test-action
         with:
           token: ${{ steps.get_installation_token.outputs.token }}
           stage-all-files: true
@@ -55,3 +78,111 @@ jobs:
       - name: Delete test branch
         run: |
           git push --force --delete origin ${{ steps.setup-test-branch.outputs.branch-name }}
+      - name: Check output
+        run: |
+          changedFilesIfAvailable=$(echo "${{ steps.test-action.outputs.commit-response }}" | jq -r '.data.createCommitOnBranch.commit.changedFilesIfAvailable')
+
+          if [[ -z "$changedFilesIfAvailable" || "$changedFilesIfAvailable" == "null" ]]; then
+            echo "Error: changedFilesIfAvailable is empty or null. Verify the output from test-action."
+            exit 1
+          fi
+
+          if [[ "$changedFilesIfAvailable" -ne 1 ]]; then
+            echo "Error: changedFilesIfAvailable is expected to be 1 but got $changedFilesIfAvailable."
+            exit 1
+          fi
+
+          echo "Validation passed: changedFilesIfAvailable is $changedFilesIfAvailable."
+  test-not-stage-all-files:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          ref: ${{ github.head_ref || github.ref }}
+      - name: Setup test branch
+        id: setup-test-branch
+        run: |
+          BRANCH_NAME="test_not_stage_all_files-$(date +%s)"
+
+          git config --global user.name 'github-actions[bot]'
+          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+
+          git checkout -b $BRANCH_NAME
+
+          echo $BRANCH_NAME > "test-file1.txt"
+          echo $BRANCH_NAME > "test-file2.txt"
+          
+          git add test-file1.txt
+          
+          echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
+      - uses: ./
+        id: test-action
+        with:
+          token: ${{ steps.get_installation_token.outputs.token }}
+          stage-all-files: false
+          commit-message: ${{ steps.setup-test-branch.outputs.branch-name }}
+      - name: Delete test branch
+        run: |
+          git push --force --delete origin ${{ steps.setup-test-branch.outputs.branch-name }}
+      - name: Check output
+        run: |
+          changedFilesIfAvailable=$(echo "${{ steps.test-action.outputs.commit-response }}" | jq -r '.data.createCommitOnBranch.commit.changedFilesIfAvailable')
+
+          if [[ -z "$changedFilesIfAvailable" || "$changedFilesIfAvailable" == "null" ]]; then
+            echo "Error: changedFilesIfAvailable is empty or null. Verify the output from test-action."
+            exit 1
+          fi
+
+          if [[ "$changedFilesIfAvailable" -ne 1 ]]; then
+            echo "Error: changedFilesIfAvailable is expected to be 1 but got $changedFilesIfAvailable."
+            exit 1
+          fi
+
+          echo "Validation passed: changedFilesIfAvailable is $changedFilesIfAvailable."
+
+  test-multiple-files:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          ref: ${{ github.head_ref || github.ref }}
+      - name: Setup test branch
+        id: setup-test-branch
+        run: |
+          BRANCH_NAME="test_multiple_files-$(date +%s)"
+
+          git config --global user.name 'github-actions[bot]'
+          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+
+          git checkout -b $BRANCH_NAME
+
+          echo $BRANCH_NAME > "test-file1.txt"
+          echo $BRANCH_NAME > "test-file2.txt"
+          
+          git add .
+          
+          echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT
+      - uses: ./
+        id: test-action
+        with:
+          token: ${{ steps.get_installation_token.outputs.token }}
+          stage-all-files: false
+          commit-message: ${{ steps.setup-test-branch.outputs.branch-name }}
+      - name: Delete test branch
+        run: |
+          git push --force --delete origin ${{ steps.setup-test-branch.outputs.branch-name }}
+      - name: Check output
+        run: |
+          changedFilesIfAvailable=$(echo "${{ steps.test-action.outputs.commit-response }}" | jq -r '.data.createCommitOnBranch.commit.changedFilesIfAvailable')
+
+          if [[ -z "$changedFilesIfAvailable" || "$changedFilesIfAvailable" == "null" ]]; then
+            echo "Error: changedFilesIfAvailable is empty or null. Verify the output from test-action."
+            exit 1
+          fi
+
+          if [[ "$changedFilesIfAvailable" -ne 2 ]]; then
+            echo "Error: changedFilesIfAvailable is expected to be 2 but got $changedFilesIfAvailable."
+            exit 1
+          fi
+
+          echo "Validation passed: changedFilesIfAvailable is $changedFilesIfAvailable."
diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -12,16 +12,129 @@ inputs:
     default: 'false'
   token:
     required: true
-    description: 'GitHub access token'
-  use-checkout-repo:
-    required: false
-    description: 'Whether to use the repo from the checked out .git directory. Defaults to false, meaning it will use the action context repo.'
-    default: 'false'
+    description: 'GitHub access token with permissions to write to repo'
 outputs:
-  commit-sha:
-    description: 'The commit hash of the new commit'
-  committed-files:
-    description: 'Array of the files that were committed'
+  commit-response:
+    description: 'The response from the graphql query'
+    value: ${{ steps.commit-changes.outputs.commit_response }}
 runs:
-  using: 'node16'
-  main: 'dist/index.js'
+  using: 'composite'
+  steps:
+    - name: Setup commit context
+      shell: bash
+      id: commit-context
+      run: |
+        # Get the remote URL (default "origin")
+        REMOTE_URL=$(git remote get-url origin)
+        echo "Remote URL: $REMOTE_URL"
+
+        # Parse the owner and repo using regex
+        if [[ "$REMOTE_URL" =~ (git@|https://)github\.com[:/](.+)/(.+?)(\.git)?$ ]]; then
+          OWNER=${BASH_REMATCH[2]}
+          REPO=${BASH_REMATCH[3]}
+          BRANCH=$(git branch --show-current)
+          echo "repo=$OWNER/$REPO" >> $GITHUB_OUTPUT
+          echo "branch=$BRANCH"
+        else
+          echo "ERROR: Invalid GitHub remote URL"
+          exit 1
+        fi
+
+    - name: Stage all files
+      if: inputs.stage-all-files == 'true'
+      shell: bash
+      run: git add .
+
+    - name: Prep file json
+      id: prep-file-json
+      shell: bash
+      run: |
+        status_output=$(git status --porcelain=v2 --branch --untracked-files=no)
+      
+        staged_additions=()
+        staged_deletions=()
+
+        while IFS= read -r line; do
+          if [[ "$line" == 1* ]]; then
+            status=$(echo "$line" | awk '{print $2}')
+            filepath=$(echo "$line" | awk '{print $NF}')
+            
+            if [[ "$status" == M || "$status" == A ]]; then
+              staged_additions+=("$filepath")
+            fi
+
+            if [[ "$status" == D ]]; then
+              staged_deletions+=("$filepath")
+            fi
+          fi
+        done <<< "$status_output"
+
+        additions_json=""
+        for filepath in "${staged_additions[@]}"; do
+          file_content=$(cat "$filepath" | base64 | tr -d '\n') # Encode file content in Base64
+          additions_json+="{\"path\":\"$filepath\",\"contents\":\"$file_content\"},"
+        done
+
+        # Strip trailing comma from JSON, if applicable
+        additions_json="[${additions_json%,}]"
+      
+        deletions_json=""
+        for filepath in "${staged_deletions[@]}"; do
+          deletions_json+="{\"path\":\"$filepath\"},"
+        done
+        
+        # Strip trailing comma from JSON, if applicable
+        deletions_json="[${deletions_json%,}]"
+        
+        if [[ "$additions_json" == "[]" && "$deletions_json" == "[]" ]]; then
+          echo "No changes to commit"
+          exit 1
+        fi
+
+        # Set outputs for the next step
+        echo "additions=$additions_json" >> $GITHUB_OUTPUT
+        echo "deletions=$deletions_json" >> $GITHUB_OUTPUT
+
+    - name: Commit changes
+      shell: bash
+      id: commit-changes
+      run: |
+        
+        branch_oid=$(git ls-remote origin refs/heads/${{ steps.commit-context.outputs.branch }} | awk '{ print $1 }')
+        
+        if [ -n "$branch_oid" ]; then
+          head_oid=$branch_oid # Use remote OID of the current branch
+        else
+          head_oid=$(git ls-remote origin HEAD | awk '{ print $1 }') # Fallback to HEAD
+        fi
+  
+        graphql_query=$(cat <<EOF
+        mutation {
+          createCommitOnBranch(
+            input: {
+              branch:
+                {
+                  repositoryNameWithOwner: "${{ steps.commit-context.outputs.repo }}",
+                  branchName: "${{ steps.commit-context.outputs.branch }}"
+                },
+              message: { headline: "${{ inputs.commit-message }}" },
+              fileChanges: {
+                additions: ${{ steps.prep-file-json.outputs.additions }},
+                deletions: ${{ steps.prep-file-json.outputs.deletions }}
+              },
+              expectedHeadOid: "$head_oid"
+            }
+          ){
+            commit {
+              url,
+              changedFilesIfAvailable
+            }
+          }
+        }
+        EOF
+        )
+        
+        response=$(gh api graphql -F "query=$graphql_query")
+        echo "commit_response=$response" >> $GITHUB_OUTPUT
+      env:
+        GH_TOKEN: ${{inputs.token}}
